### ISSUE TITLE
Feature request: chunked blob upload

### ISSUE THREAD

**Issue by micw** [davedoesdev/dxf#11]
To copy a blob between registries, it needs to be downloaded to a file, then uploaded again. It would be great if the push_blob would also be usable with a digest + chunk iterator so that no file must be created.

**Comment by davedoesdev** [comment]
Good idea. Let me think about implementing it...

**Comment by davedoesdev** [comment]
Implemented in https://github.com/davedoesdev/dxf/commit/2d52b053f744e25eecc82d7de85772ef1686bcea

Released as 5.2.0.

@micw please let me know if it works for you.

**Comment by micw** [comment]
Works like a charm, thank you a lot!
