### ISSUE TITLE
jws is unmaintained, switch to jwcrypto

### ISSUE THREAD

**Issue by mrueg** [davedoesdev/dxf#12]
See also: https://github.com/brianloveswords/python-jws/commit/9228dcc83dccfd4dde9df12f491b8d92c95a874a

https://github.com/latchset/jwcrypto

**Comment by davedoesdev** [comment]
@mrueg thanks for raising this issue, appreciate it. It is on my radar, should get to it within a couple of weeks. There are a couple of other modules I need to change too.

**Comment by davedoesdev** [comment]
@mrueg version 6.0.0 is now published which uses jwcrypto.
Please let me know if it works for you.

**Comment by mrueg** [comment]
@davedoesdev thanks for the quick fix! Can you push tags to github as well please?

**Comment by davedoesdev** [comment]
tag `v6.0.0` pushed
