### ISSUE TITLE
dxf list-repos doesn't show all repositories (needs pagination support)

### ISSUE THREAD

**Issue by mrueg** [davedoesdev/dxf#14]
The docker registry does pagination on the catalog endpoint:
https://registry-url/v2/_catalog?last=seenimagefrompreviouspage

Currently `dxf list-repos` only returns the first n images.

**Comment by davedoesdev** [comment]
Ditto for `list_aliases`

**Comment by davedoesdev** [comment]
Closed by https://github.com/davedoesdev/dxf/commit/9e40cc7ab164f608bffe1b783773711f31776681
