### ISSUE TITLE
Implement a command to get the digest of an alias

### ISSUE THREAD

**Issue by mrueg** [davedoesdev/dxf#16]
the internal get_manifest() function already provides information from the registry:
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 32434,
      "digest": "sha256:$MYHASH"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1253243212,
         "digest": "sha256:anotherhash"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12211986,
         "digest": "sha256:anotherhash"
      }
   ]
}
```
while docker inspect provides:
```
$ docker inspect host/foo:tag --format='{{.Id}}'
$ sha256:$MYHASH
```
It would be nice, if an additional command `get-digest`  could fetch the id from an alias, so it's easy to compare if the local and remote image match without pulling the image.

**Comment by davedoesdev** [comment]
Where does the id come from?

**Comment by davedoesdev** [comment]
{{config/digest}} ?

**Comment by mrueg** [comment]
Yes, it's config["digest"]

**Comment by davedoesdev** [comment]
Can multiple images share the same config?

**Comment by mrueg** [comment]
See also: https://github.com/docker/distribution/issues/1662#issuecomment-213079540
"The image id used within docker can be found in this manifest as config.digest"
"The best way to determine this is to compare the image id within a manifest to a local image id. This does require pulling and parsing the manifest."

**Comment by davedoesdev** [comment]
Yep, thanks. Also: http://windsock.io/explaining-docker-image-ids/

> The image ID is also a digest, and is a computed SHA256 hash of the image configuration object, which contains the digests of the layers that contribute to the image's filesystem definition.

In that case I think the command should be named `get-config`, what do you think?

I've implemented something but need to add tests.

**Comment by mrueg** [comment]
`get-config` seems a bit off, maybe `get-digest`?

**Comment by davedoesdev** [comment]
Fixed in 6.3.0

**Comment by mrueg** [comment]
Thanks a lot! In case you're interested, I've packaged dxf for Gentoo Linux: https://packages.gentoo.org/packages/app-admin/dxf

**Comment by mrueg** [comment]
@davedoesdev just curious, why did you split the sha256: prefix from get-digest output?

**Comment by davedoesdev** [comment]
No particular reason, just to be consistent with the other digest printing (e.g.`get-alias`).
Do you think they should all be prefaced with the digest method?

**Comment by davedoesdev** [comment]
@mrueg v7.0.0 keeps the `sha256:` prefix.
