### ISSUE TITLE
Support creating a new `DXF` class from an existing `DXFBase`

### ISSUE THREAD

**Issue by leesdolphin** [davedoesdev/dxf#19]
I'm trying to iterate over the contents of a registry, so I initially create a `DXFBase` class(as I have no `repo`); however to then drill-down into the repo I need to create a brand new object using the exact same properties as the first. It'd be great if there was a method that created a `DXF` object that shared some information like URLs and sessions.

**Comment by davedoesdev** [comment]
Good idea, I'll see what makes sense in the code

**Comment by davedoesdev** [comment]
@leesdolphin could you try version 7.2.0 please?

I added this class method: https://rawgit-gjgjyaqiln.now.sh/davedoesdev/dxf/master/docs/_build/html/index.html#dxf.DXF.from_base

Does it address your use case?

**Comment by davedoesdev** [comment]
Fixed in 7.2.0
