### ISSUE TITLE
del-alias: 405 Client Error: Method Not Allowed

### ISSUE THREAD

**Issue by wjentner** [davedoesdev/dxf#25]
I'm trying to delete a tag from the docker registry.

```bash
$ export DXF_HOST=index.docker.io
$ export DXF_USERNAME=...
$ export DXF_PASSWORD=...

$ dxf list-aliases sisu4u/unity3d-test
2018.3.7f1-android
2018.3.7f1-facebook
2018.3.7f1-ios
2018.3.7f1-mac
2018.3.7f1-unity
2018.3.7f1-webgl
2018.3.7f1-windows
2018.3.7f1
2019.1.3f1-android
2019.1.3f1-facebook
2019.1.3f1-ios
2019.1.3f1-mac
2019.1.3f1-unity
2019.1.3f1-webgl
2019.1.3f1-windows
2019.1.3f1
latest

$ dxf del-alias sisu4u/unity3d-test latest
Traceback (most recent call last):
  File "/usr/local/bin/dxf", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/dxf/main.py", line 206, in main
    exit(doit(sys.argv[1:], os.environ))
  File "/usr/local/lib/python3.7/site-packages/dxf/main.py", line 193, in doit
    _doit()
  File "/usr/local/lib/python3.7/site-packages/dxf/main.py", line 171, in _doit
    for dgst in dxf_obj.del_alias(name):
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 728, in del_alias
    self._request('delete', 'manifests/{}'.format(dcd))
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 376, in _request
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 225, in _base_request
    _raise_for_status(r)
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 77, in _raise_for_status
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://index.docker.io/v2/sisu4u/unity3d-test/manifests/sha256:c346e1c10d901c660d824b48fb327ac62f936b8dfebdb6bb47d73a1dcd832acf
```

With my own script I can successfully delete tags:
```python
def _del_tag(namespace, repo, tag, token):
    print(('Commence to delete %s/%s:%s ...' % (namespace, repo, tag)))
    url = 'https://hub.docker.com/v2/repositories/%s/%s/tags/%s/' % (namespace, repo, tag)
    headers = {
        'Authorization': 'JWT %s' % token
    }
    request = Request(url=url, headers=headers)
    request.get_method = lambda: 'DELETE'
    try:
        opener = build_opener(HTTPHandler)
        opener.open(request)
        print(('%s/%s:%s deleted successfully.' % (namespace, repo, tag)))
        # body = response.read().decode('utf-8')
    # If we have an HTTPError, try to follow the response
    except HTTPError as err:
        print(("Failed to delete tag. Error: %s" % err))
        raise
```

**Comment by davedoesdev** [comment]
Thanks for the bug report, I'll try to get time to investigate.

Strange that deleting by tags works - I don't think the tags API has been
merged yet:

https://github.com/docker/distribution/pull/2169

The only supported way is to look up the digest and then delete by manifest.

**Comment by wjentner** [comment]
I think this was reverse-engineered through the docker-hub api.
I tried it again right now and the browser shows me that the following URL is called with DELETE: https://cloud.docker.com/v2/repositories/sisu4u/unity3d-test/tags/2018.3.7f1-unity/

**Comment by davedoesdev** [comment]
Strange because the docs still say onl GET TAG: https://docs.docker.com/registry/spec/api/#tags

**Comment by davedoesdev** [comment]
I just pulled the latest registry:2 and the tests pass for me locally.

**Comment by davedoesdev** [comment]
@wjentner is `cloud.docker.com` the same as `index.docker.io`?

**Comment by wjentner** [comment]
I don't think so. I think cloud.docker.com is actually an extended (?) API that docker uses for their own registry.
You can simply go on https://hub.docker.com and have the dev tools open to see what's going on. For example, listing tags is done like this:
https://hub.docker.com/v2/repositories/gableroux/unity3d/tags/?page_size=100&page=1
whereas 100 seems to be the maximum for page_size.

**Comment by wjentner** [comment]
Using
```bash
$ export DXF_HOST=cloud.docker.com
```

results in:
```bash
$ dxf list-aliases gableroux/unity3d
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dxf/main.py", line 193, in doit
    _doit()
  File "/usr/local/lib/python3.7/site-packages/dxf/main.py", line 185, in _doit
    for name in dxf_obj.list_aliases(iterate=True):
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 132, in __iter__
    response = self._meth('get', self._path, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 376, in _request
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 225, in _base_request
    _raise_for_status(r)
  File "/usr/local/lib/python3.7/site-packages/dxf/__init__.py", line 77, in _raise_for_status
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cloud.docker.com/v2/gableroux/unity3d/tags/list
```

**Comment by davedoesdev** [comment]
OK I've repro'd against index.docker.io

**Comment by davedoesdev** [comment]
It may well be another manifestation of https://github.com/docker/distribution/issues/2395

**Comment by davedoesdev** [comment]
del_alias gets the DCD, which gets the application/vnd.docker.distribution.manifest.v2+json
This is the value that's been wrong in the Docker online registry for 18 months now.
It returns the hash of the manifest list instead of the manifest.
So we'll ask to delete the manifest list which I don't think is allowed (it's the thing that put as the alias).

**Comment by davedoesdev** [comment]
Btw, this issue is relevant: https://github.com/docker/distribution/issues/1566#issuecomment-205484205
It explains you have to delete the manifest by DCD which is what dxf does.

**Comment by davedoesdev** [comment]
The tests check that deleting an alias works by listing the aliases afterwards.

**Comment by davedoesdev** [comment]
@wjentner what do you think? Leave this open until https://github.com/docker/distribution/issues/2395 gets fixed?

**Comment by wjentner** [comment]
Sure I don't think it makes sense right now to have a workaround.

**Comment by davedoesdev** [comment]
@wjentner the public registry seems to be returning the correct hash now.

However, delete is turned off: https://github.com/docker/hub-feedback/issues/1759

Basically, Docker Hub doesn't exactly implement the documented registry API. There is a separate, undocumented, API that the Docker CLI uses. Bad form IMHO.

I do have `set-alias` working with Docker Hub though (coming in v7.5.2 of dxf).

**Comment by davedoesdev** [comment]
It looks like even Google didn't bother supporting Docker Hub: https://github.com/google/go-containerregistry/issues/136#issuecomment-530543423

@jonjohnsonjr is that correct?

**Comment by jonjohnsonjr** [comment]
Right. If they don't want to support their own API, that's fine 😄 

I'd prefer it if they would propose a new mechanism for blocking accidental deletes, but I'm not going to bend over backwards to call their registry-specific undocumented API as a workaround.

**Comment by davedoesdev** [comment]
@wjentner OK to close this issue? The public registry doesn't confirm to the spec.

**Comment by wjentner** [comment]
@davedoesdev sure it doesn't make sense probing APIs to see whether they support certain actions or not. Sad to see that docker seems to continue their weird approach of not obeying their own specs.
