### ISSUE TITLE
Support for gcr.io

### ISSUE THREAD

**Issue by hasiotis** [davedoesdev/dxf#28]
This is probably a problem on gcr.io side but it would be nice if we can put a workaround. The following sample code fails
 ```
#!/usr/bin/env python3

import sys
import json

from dxf import DXFBase


def auth(dxf, response):
    creds = json.loads(sys.stdin.read())
    dxf.authenticate(creds['Username'], creds['Secret'], response=response)


dxf = DXFBase('gcr.io', auth)
repos = dxf.list_repos()
print(repos)
```
when run with:
```
echo gcr.io | gcloud auth docker-helper get | ./dxf-gcr.py
```
The problem seems to be lack of "scope" on www-authenticate header from gcr.io.
```
$ http -h https://gcr.io/v2/_catalog | grep -i WWW-Authenticate
WWW-Authenticate: Bearer realm="https://gcr.io/v2/token",service="gcr.io"
```
while dockerhub reply is as follows:
```
$ http -h https://registry-1.docker.io/v2/_catalog | grep -i WWW-Authenticate
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="registry:catalog:*"
```
The possible workaround could be something like this:
```
diff --git dxf/__init__.py dxf/__init__.py
index 8b60245..678a7d4 100644
--- dxf/__init__.py
+++ dxf/__init__.py
@@ -288,6 +288,8 @@ class DXFBase(object):
                 scope = 'repository:' + self._repo + ':' + ','.join(actions)
             elif 'scope' in info:
                 scope = info['scope']
+            elif not self._repo:
+                scope = 'registry:catalog:*'
             else:
                 scope = ''
             url_parts = list(urlparse.urlparse(info['realm']))
```

Thanks

**Comment by davedoesdev** [comment]
@hasiotis thanks for raising this issue and good catch!
It does seem like we need to use `registry:catalog:*` scope:

https://stackoverflow.com/questions/44783736/how-to-list-images-and-tags-from-the-gcr-io-docker-registry-using-the-http-api

Your workaround does seem to work (well, I get unauthorized with dummy credentials, I don't have a GCR account).

I'm just mulling over whether it's best to hardcode it or not.

**Comment by davedoesdev** [comment]
I think it is safe to hardcode it since Docker hub/distribution will always return the scope and we're only setting it for the non-repo case. Furthermore, the non-repo case only has `list_repos()` as a method which uses `_catalog`.

@hasiotis what do you think?

**Comment by davedoesdev** [comment]
@hasiotis I've published this as version 7.5.4. If you could try it that would be great.
Thanks again.

**Comment by hasiotis** [comment]
@davedoesdev I just verified that is working as expected. Probably even the hardcoded version is safe enough. Anyway, please close the ticket. Thanks!

**Comment by davedoesdev** [comment]
@hasiotis great. Thanks for finding and fixing the issue appreciate it.
I think the hardcoded version should be fine as it should only apply in the non-repo, catalog case.
