### ISSUE TITLE
Mention of get-blob in README 

### ISSUE THREAD

**Issue by arthurlogilab** [davedoesdev/dxf#32]
For set-alias there is a mension of `get-blob` which is not in documentation, is it `get-alias` ?

**Comment by davedoesdev** [comment]
@arthurlogilab thanks for noticing this. It should be `push-blob` or `get-alias`. I'll fix that, thanks again.

**Comment by davedoesdev** [comment]
Closed by https://github.com/davedoesdev/dxf/commit/2817432541a4366958c1ab58467c8f866978cc44
