### ISSUE TITLE
List tags for specific images

### ISSUE THREAD

**Issue by AstraLuma** [davedoesdev/dxf#34]
https://docs.docker.com/registry/spec/api/#listing-image-tags

**Comment by AstraLuma** [comment]
oops, i'm a dummy. you can ignore this.

(For those that don't get it, `DXF` has the image you're operating on already. It's repo-global operations like listing all images that's a problem.)

**Comment by davedoesdev** [comment]
@AstraLuma does `list-aliases` do what you want?

**Comment by AstraLuma** [comment]
I'm using the API, not the CLI, but yeah. Having a client instance bound to a specific repository is just throwing me.
