### ISSUE TITLE
Can I add a note about my project in dxf's readme?

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [davedoesdev/dxf#35]
Hi! Thanks for this awesome lib!

I used it to make a tool that we need in my company: https://github.com/gabrieldemarmiesse/docker-charon

Since some users who come across dxf might have this use case, I would like to mention docker-charon in dxf's README. So that users don't reinventing the wheel :)

**Comment by davedoesdev** [comment]
@gabrieldemarmiesse happy to do that - would you like to make a PR with your note?

**Comment by gabrieldemarmiesse** [comment]
yes, done! Thanks!

**Comment by davedoesdev** [comment]
Thanks, appreciate it - will hopefully get round to merging it in the next couple of days.
