### ISSUE TITLE
Add a function to do "Cross Repository Blob Mount"

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [davedoesdev/dxf#37]
Hello there! 
I'm working on docker-charon, which uses heavily DFX. While the size of the zip that contains the docker images is heavily reduced because we only take the diff,
we can only compute this diff *within the same repository*. We could do even better if we had the option to mount blobs from one repository to another.
Such an option is already available in the registry v2 api. But I don't see a function in DFX to mount blobs from one repository to another.

https://docs.docker.com/registry/spec/api/#pushing-an-image

Would you be interested in such a function? If yes I can make a pull request :)

I wonder how the CLI does to automatically detect if blobs are in another repository. It would seem unlikely that the CLI is querying all the repositories one by one.

If we know how the CLI does it, maybe we can implement the same and do an auto-skip when calling "push_blob"?

**Comment by davedoesdev** [comment]
Yes, this would be useful. 
Is this the CLI code? https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/manifest/push.go#L113

**Comment by gabrieldemarmiesse** [comment]
I'm not very good in go. I read the code but didn't find how they could automaticallymount blobs.

I'll juste implement a simple function first: `dxf.mount_blob(digest: str, other_repository: str)` if that's okay with you.

**Comment by davedoesdev** [comment]
@gabrieldemarmiesse I implemented mount blob in v7.8.0.

Having looked at the CLI code I don't think it detects automatically whether the blob is in the registry. It knows which repo the blob is mounted from.

**Comment by davedoesdev** [comment]
I think the client must use the Docker manifest file and when building decide to do mounts instead of upload.

**Comment by davedoesdev** [comment]
The proposal was here: https://github.com/distribution/distribution/issues/634

**Comment by davedoesdev** [comment]
Looks like client code went in here: https://github.com/moby/moby/pull/19109

**Comment by gabrieldemarmiesse** [comment]
I'll have to read that in more detail. 
I'm trying to understand how the registry client get the info. 

So that means that if I do
"docker build -t gabrieldemarmiesse/hello ."
and that the dockerfile has a "FROM python:3.8", then the client (in this case buildx) keeps track of where each layer comes from? So that if I push the new image to dockerhub, the client doesn't have to query the registry to know that most layers come from the repository 'python'? 

Am I correct?

**Comment by davedoesdev** [comment]
I tracked it down. They have a service which runs in the daemon: 

https://github.com/moby/moby/blob/b88acf7a7a571b0fe054b8315c79caa16b0c92df/daemon/images/service.go#L40
https://github.com/moby/moby/blob/d116e12c6da277724914fecf996a90db860e3963/daemon/daemon.go#L1048

It keeps track of things so when you push an existing blob it knows where to mount it.

**Comment by davedoesdev** [comment]
Implementation of the store here: https://github.com/moby/moby/blob/d116e12c6da277724914fecf996a90db860e3963/distribution/metadata/metadata.go#L31

We'd have to read this store from dxf. At the moment dxf doesn't have any ties to the docker client. I'm not sure I want to add this, need to think about it.

**Comment by gabrieldemarmiesse** [comment]
I believe too that it doesn't fit into DXF. Even if you implemented it I would not use it since my tool docker-charon bypass the docker engine to package layers.

**Comment by davedoesdev** [comment]
@gabrieldemarmiesse OK thanks for the info. Is it okay if I close this issue?

Summary for anyone coming later:

- mount blob implemented in v7.8.0 of dxf
- automatically determining a mount exists is currently outside the remit of dxf. The docker client does this by keeping track of pulls and pushes in its daemon and storing the info on disk.

**Comment by gabrieldemarmiesse** [comment]
We can close this issue. Thanks a lot for implementing it! I'll use this in docker-charon :)
