### ISSUE TITLE
Org-less repos not supported

### ISSUE THREAD

**Issue by umdstu** [davedoesdev/dxf#38]
@davedoesdev

I recently came across an issue with Docker repos that did not include an organization value in the path. I came across [https://github.com/davedoesdev/dxf/issues/31](this) and think I see what might be happening. At least in my case.

Two component repos work fine, eg. docker.io/curlimages/curl, docker.io/bitnami/python, and docker.io/circleci/openjdk but 1 component repos fail to authenticate every time, eg. docker.io/python, docker.io/openjdk and docker.io/eclipse-temurin.

I was running 7.7.2, because pip refused to install 7.7.3 because of a dependency conflict, but ultimately got both installed and both fail to work for single component repos.

I poked around some and it looks like it may be how you're setting `_repo_path`. For single component repos, like python, java, and openjdk, you need to prepend `library` to the API call, eg. `registry-1.docker.io/python` needs to be `registry-1.docker.io/library/python` where `host=registry-1.docker.io` and `repo= library/python`). I modified your code to this and it seemed to work, but could use come cleaning up.

```python
repo_parts = repo.split("/")
if len(repo_parts) == 1:
    self._repo = "library/" + repo
    self._repo_path = ("library/" + repo + "/") if repo else ""
else:
    self._repo =  repo
    self._repo_path = (repo + "/") if repo else ""
```
It seems as though the "organization" for simple repositories is `library`, and using this allows this package to work with these types of repos.

**Comment by davedoesdev** [comment]
@umdstu thanks very much for this, appreciate it.
I'll take a look as soon as I get a moment.
Thanks again

**Comment by davedoesdev** [comment]
@umdstu I've implemented this in v7.7.4. Let me know if it works for you. Thanks again for digging into this and identifying the problem.

**Comment by umdstu** [comment]
Awesome! Happy to help, thanks for the quick work. I'll test it out Monday and report back

**Comment by umdstu** [comment]
Seems to be working @davedoesdev , thank you again for the quick turn around!
