### ISSUE TITLE
Resolve a tag to its digest

### ISSUE THREAD

**Issue by ChristianCiach** [davedoesdev/dxf#41]
I want to resolve a tag of an image to its digest (to then download the cosign signature of the image, that uses the digest of the signed image as the prefix of the tag of the signature-image).

I've tried `get_digest`, `get_alias` and `get_manifest`, but none of these get me the digest that I am looking for.

The digest I am looking for can be retrieved by using `docker manifest inspect -v` (the `-v` is imporant). For example:

```
$ docker manifest inspect my-registry.local/project/repo:1.0.0 -v
{
	"Ref": "my-registry.local/project/repo:1.0.0",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:2613d8f5b647d16835739e8432e5272733aae1325d12d8986e82696e84f91b31",
		"size": 527,
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}
	},
	"SchemaV2Manifest": {
		"schemaVersion": 2,
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"config": {
			"mediaType": "application/vnd.docker.container.image.v1+json",
			"size": 708,
			"digest": "sha256:76ba57e0638f58bcbccaa0f6639226486b00651fd9eef03f21443c7b3ee72208"
		},
		"layers": [
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 2289926,
				"digest": "sha256:6a1aaa55c0246737ca422553617a0dcbe2fef0e626db2a00b455fd925f95dd92"
			}
		]
	}
}
```

The digest I need is the `sha256:2613d8f5b647d16835739e8432e5272733aae1325d12d8986e82696e84f91b31`.

The same digest can also be retrieved by using `skopeo inspect`:
```
$ skopeo inspect docker://my-registry.local/project/repo:1.0.0
{
    "Name": "my-registry.local/project/repo:1.0.0",
    "Digest": "sha256:2613d8f5b647d16835739e8432e5272733aae1325d12d8986e82696e84f91b31",
    "RepoTags": [
        "1.0.0",
        "sha256-2613d8f5b647d16835739e8432e5272733aae1325d12d8986e82696e84f91b31.sbom",
        "sha256-2613d8f5b647d16835739e8432e5272733aae1325d12d8986e82696e84f91b31.sig",
    ],
```
Is there a way to retrieve this digest using DXF? I would like to do this in pure python if possible.

**Comment by ChristianCiach** [comment]
`_get_dcd(alias)` gives me what I am looking for, but unfortunately it's private..

**Comment by ChristianCiach** [comment]
Well, it looks like I cannot use this DFX to read cosign signatures anyway. Cosign signatures are OCI artifacts and OCI registries like Harbor only show them when using the `Accept: application/vnd.oci.image.manifest.v1+json` header. Unfortunately DFX is hardcoded to use the mime type `application/vnd.docker.distribution.manifest.v2+json`.

When trying to retrieve a manifest using the currently hardcoded mime type, Harbor sends a 404 response with the body:
```
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI manifest found, but accept header does not support OCI manifests"}]}
```

The very first line of the README of DXF says:
> Python module and command-line tool for storing and retrieving data in a **Docker registry**.

So, supporting OCI registries is probably out of scope for this project. Feel free to close this issue if you agree :) Unfortunately there doesn't seem to be another python package that comes *this* close to supporting my use-case.

**Comment by davedoesdev** [comment]
@ChristianCiach I'll leave this open as a prompt to implement support for OCI registries.
However it may be some time before I look into it as I just don't have much time.

**Comment by davedoesdev** [comment]
@ChristianCiach #45 has added some support OCI registries.
Do you think it's enough for what you want?

**Comment by ChristianCiach** [comment]
Thanks for pinging me! Looking at the code that has been merged, it looks like it would satisty my requirements. But by now I've solved my use case by writing my own code, so I will probably won't have an opportunity to actually try out the changes, as I don't have the need anymore.

I still think it would be good to make `_get_dcd(alias)` public, possibly using another name. This function returns the digest that I was actually looking for. This is what this issue was originally about :D

**Comment by davedoesdev** [comment]
Thanks, I'll look at making that method public in case it's of use to others.

**Comment by ChristianCiach** [comment]
That being said, I don't think other tools like skopeo (as shown in my description) actually extract *this* digest from the DCD header, as it is very docker specific. I am using my smartphone right now, so browsing the source code is a pain, but I was able to hunt skopeos implementation down to this: https://github.com/containers/image/blob/34522e9f2ba90c7af1669825db4e6cf09c32a10f/internal/manifest/manifest.go#L108 

It looks like Skopeo and other tools based on `containers/image` actually compute the digest themselves by hashing the manifest blob. Interesting.

**Comment by davedoesdev** [comment]
I _think_ that ends up [here](https://github.com/opencontainers/go-digest/blob/master/digest.go#L92) where `Canonical` is sha256.

**Comment by davedoesdev** [comment]
Or for V2s1 sigs it parses the sig returned

**Comment by davedoesdev** [comment]
Currently dxf is using the Docker-Content-Digest header only in `del_alias`, so that it only has to make a HEAD request for the manifest.

**Comment by davedoesdev** [comment]
This line is interesting:

https://github.com/containers/image/blob/92f19481f04cc6ae027101caf91d65c419d05cb1/docker/docker_image_dest.go#L476

It suggests Docker-Content-Digest header is optional.

**Comment by davedoesdev** [comment]
https://github.com/opencontainers/distribution-spec/blob/ec90a2af85fe4d612cf801e1815b95bfa40ae72b/spec.md#checking-if-content-exists-in-the-registry

> A HEAD request to an existing blob or manifest URL MUST return 200 OK. A successful response SHOULD contain the digest of the uploaded blob in the header Docker-Content-Digest.

**Comment by davedoesdev** [comment]
I'm thinking of removing `_get_dcd` and adjusting the rest of the code to treat Docker-Content-Digest as optional where necessary.

**Comment by davedoesdev** [comment]
OK all uses of Docker-Content-Digest are now optional in version 10.0.0.

For your original question, and for anyone else wanting similar, is hashing the result of calling `get_manifest` enough?

As per the README, dxf isn't really targetted at Docker image specific functionality.
