### ISSUE TITLE
get_manifest is unreliable in its return type

### ISSUE THREAD

**Issue by farcaller** [davedoesdev/dxf#49]
I'm not exactly sure for the triggering conditions, but get_manifest will return a str when I talk to docker hub (registry-1.docker.io/freshrss/freshrss) and a dict when I talk to ghcr.io (ghcr.io/tailscale/golink) in the same loop but different DXF instances.

**Comment by davedoesdev** [comment]
The return type depends on whether the manifest is multi-arch. Per the [API docs](https://rawgit-now.netlify.app/davedoesdev/dxf/master/docs/_build/html/index.html):

> Returns: The manifest as a string (JSON). For multi-arch aliases, a dict of manifest per platform.

**Comment by davedoesdev** [comment]
If you supply the platform argument, the manifest for that platform will be returned as a string
