### ISSUE TITLE
support old style manifests

### ISSUE THREAD

**Issue by graingert** [davedoesdev/dxf#5]
I'm running using Amazon's ECR and that requires support for v2 API auth and V1 schemas.

It would be great to drop down to V1 schemas where necessary

**Comment by davedoesdev** [comment]
Should be possible - I moved to v2 schema here: https://github.com/davedoesdev/dxf/commit/eef318aef008e97845bc54bad52c8d3a1f3bea6b

Won't get done short term though :(

**Comment by davedoesdev** [comment]
@graingert it looks like ECR is rolling out v2 schema support soon: https://forums.aws.amazon.com/thread.jspa?threadID=245574

**Comment by graingert** [comment]
Ah neat, but I'm looking to add this support to shipwright where I'll be
working with various different registries.

**Comment by davedoesdev** [comment]
@graingert shipwright looks neat.
Have you tried using dxf yet? I really developed it for storing data, not manipulating existing Docker images.

**Comment by graingert** [comment]
I've played with it. I mostly want to make it possible to retag images without pulling and pushing them.

**Comment by davedoesdev** [comment]
Ah okay. I'll see if I can make some time but it might be a few days.

**Comment by davedoesdev** [comment]
@graingert please try version 4.0.1
It falls back to schema v1 (at least in the tests). Tested against latest registry and registry 2.2 (which only supported schema v1).

**Comment by davedoesdev** [comment]
Closed by v4.0.1
