### ISSUE TITLE
Request for head manifest api

### ISSUE THREAD

**Issue by msadiq058** [davedoesdev/dxf#51]
I need to validate whether the given tag exists or not.
get_manifest_and_response API is available which returns detail manifest but for docker-hub, there is a [rate-limit](https://docs.docker.com/docker-hub/download-rate-limit/#whats-the-download-rate-limit-on-docker-hub) on it.

There is another HEAD API that can be used to validate the existence. https://github.com/distribution/distribution/blob/5cb406d511b7b9163bff9b6439072e4892e5ae3b/docs/spec/api.md#existing-manifests

Golang clients support this feature https://github.com/regclient/regclient/blob/main/docs/regctl.md#manifest-commands

If required I can contribute to this, please let me know the contribution guidelines.

**Comment by davedoesdev** [comment]
Thanks, I'll look into it when I get some time

**Comment by davedoesdev** [comment]
Thanks for your PR @msadiq058 - merged

**Comment by msadiq058** [comment]
@davedoesdev thanks for accepting the contribution.
When would the changes be available on PyPI?

**Comment by davedoesdev** [comment]
@msadiq058 should be there now
