### ISSUE TITLE
Cannot auth on registry that return 200 and empty _catalog for anonymous users

### ISSUE THREAD

**Issue by Jean-Daniel** [davedoesdev/dxf#54]
DXF bypass authorization if the response is OK, but some registry (`zot`) returns an empty _catalog and a HTTP 200 OK response for anonymous users with all required `www-authenticate` headers.

While I understand it would be complex to fix that for all client methods (`list_repos`, …), DXF should at least provides an escape hatch, and let the client force `DXF.authenticate()` to parse the response header and authenticate even if the result is 200 OK, so it would be possible to call something like `dxf.authenticate("user", "password", force=True)` to login, and then be able to fully use the registry API.

**Comment by davedoesdev** [comment]
@Jean-Daniel I've separated the logic into the [`_response_needs_auth`](https://github.com/davedoesdev/dxf/blob/master/dxf/__init__.py#L237). Could you create a derived class and override this method to suit?

**Comment by davedoesdev** [comment]
@Jean-Daniel have you had a chance to try this?
